# -*- coding: utf-8 -*-
"""Untitled74.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yZ3TVh4HPxDXYy-5PSktBNMGnrAisqpg
"""

from google.colab import files
uploaded=files.upload()

!pip install kaggle

!mkdir -p /root/.kaggle
!mv "kaggle (1).json" /root/.kaggle/kaggle.json
!chmod 600 /root/.kaggle/kaggle.json

!kaggle kernels output madhiarasan/keyword -p /content/

!pip install spacy_transformers

import spacy_transformers

import spacy
nlp=spacy.load('/content/model-best')

with open('/content/config.txt') as f:
  text=f.read()

doc=nlp(text)
doc

import json

def extract_keywords_and_save(nlp, text):
    # Process the input text using the pre-trained spaCy model
    doc = nlp(text)

    # Extract entities and print them
    print("Entities:")
    for ent in doc.ents:
        print(ent.text, ent.label_)

    # Organize keywords in the specified output_data structure
    output_data = {
        "job_title": "",
        "must_have": [],
        "good_to_have": [],
        "locations": [],
        "experiences": "",
    }

    seen_skills = set()
    for ent in doc.ents:
        if ent.text not in seen_skills:
            if ent.label_ == "MUST HAVE":
                output_data["must_have"].append(ent.text)
            elif ent.label_ == "GOOD TO HAVE":
                output_data["good_to_have"].append(ent.text)
            elif ent.label_ == "LOCATION":
                output_data["locations"].append(ent.text)
            elif ent.label_ == "EXPERIENCE":
                output_data["experiences"] = ent.text
            elif ent.label_=="JOB TITLE":
                output_data['job_title']=ent.text

            seen_skills.add(ent.text)

    print(json.dumps(output_data, indent=4))

    # Save the output_data in a JSON file
    with open("/content/output_data.json", "w") as f:
        json.dump(output_data, f, indent=4)

extract_keywords_and_save(nlp, text)

